#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2021/12/29
#=======================

# using case command
case $USER in
rich | barbara)
	echo "Welcome, $USER"
	echo "Please enjoy your visit"
	;;
testing)
	echo "Special testing account"
	;;
jessica)
	echo "Do not foreget to log off when you're done"
	;;
*)
	echo "Sorry, you are not allowed here"
	;;
esac
