#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2021/12/29
#=======================

# testing compound comparisons

if [ -d $HOME ] && [ -w $HOME/testing ]
then
	echo "The file exists and you can write to it"
else
	echo "I cannot write to the file"
fi
