#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2021/12/29
#=======================

# using double paranthesis

val1=10

if (( $val1 ** 2 > 90 ))
then
	(( val2 = $val1 ** 2 ))
	echo "The square of $val1 is $val2"
fi
