#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2021/12/29
#=======================

# using pattern matching
if [[ $USER == r* ]]
then
	echo "Hello $USER"
else
	echo "Sorry, I do not know you"
fi
