#!/bin/dash
#=======================
# Author : Ali Moradzade
# Created: 2022/01/24
#=======================

# testing mathematical operations

value1=10
value2=15

value3=$(( $value1 * $value2 ))
echo "The answer is $value3"
