#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2022/01/11
#=======================

# testing the exit status of a function

func1() {
	ls -l badfile
	echo "trying to display a non-existent file"
}

echo "testing the function: "
func1
echo "The exit status is: $?"
