#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2022/01/11
#=======================

# testing the exit status of a function

func1() {
	echo "trying to display a non-existent file"
	ls -l badfile
}

echo "testing the function: "
func1
echo "The exit status is: $?"
