#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2022/01/12
#=======================

# array variable to function test

function testit {
	local newarray=($(echo "$@"))
	echo "The new array value is: ${newarray[*]}"
}

myarray=(1 2 3 4 5)
echo "The original array is ${myarray[*]}"
testit ${myarray[*]}
