#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2022/01/12
#=======================

# trying to access script parameters inside a function good way

function func7 {
	echo $[ $1 * $2 ]
}

if [ $# -eq 2 ]
then
	value=$(func7 $1 $2)
	echo "The result is $value"
else
	echo "Usage: $(basename $0) a b"
fi
