#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2022/01/11
#=======================

# using a function in a script

function func1 {
	echo "This is an example of a function"
}

for ((count = 1; count <= 5; count++))
do
	func1
done

echo "This is the end of the loop"
func1
echo "Now this is tne end of the script"
