#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2022/01/29
#=======================

# sending multiple commands to mysql

MYSQL=$(which mysql)
DATABASE_NAME=mytest
USER=ali

$MYSQL $DATABASE_NAME -u $USER << EOF
show tables;

select * 
from employees
where salary > 4000;
EOF

