#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2022/01/10
#=======================

# test using at command redirecting out and err

echo "This script ran at $(date +%B%d,%T)" > test13b.out
echo >> test13b.out
sleep 5
echo "This is the script's end..." >> test13b.out
