#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2022/01/10
#=======================

# test using at command

echo "This script ran at $(date +%B%d,%T)"
echo
sleep 5
echo "This is the script's end ..."
