#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2022/01/09
#=======================

# trapping the script exit

trap "echo Goodbye ..." EXIT

count=1
while [ $count -le 5 ]
do
	echo "Loop #$count"
	sleep 1
	count=$[ $count + 1 ]
done
