#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2021/12/31
#=======================

# redirecting the for output to a file

file=test.txt
echo "Writing to $file ..."

for ((a = 1; a < 10; a++))
do
	echo "The number is $a"
done > $file
echo "The command is finished."
