#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2021/12/31
#=======================

# process new user accounts

input="users.csv"
while IFS=',' read -r userid name
do
	echo "adding $userid"
	useradd -c "$name" -m $userid
done < "$input"
