#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2022/01/03
#=======================

# redirecting all output to a file
exec 1>testout

echo "This is a test of redirecting all output"
echo "from a script to another file."
echo "Without having to redirect every individual line"
