#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2022/01/04
#=======================

# testing input/output file descriptor

exec 3<> testfile
read line <&3
echo "Read: $line"
echo "This is a test line" >&3
