#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2021/12/30
#=======================

# an example of how to properly define values

for test in Nevada "New Hampshire" "New Mexico" "New York" "North Carolina" 
do
	echo "Now going to $test"
done
