#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2021/12/30
#=======================

# reading values from a file
file="states"

IFS=$'\n'
for state in $(cat $file)
do
	echo "Visit beautiful $state"
done
