#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2021/12/30
#=======================

# using until command
var=100

until echo $var
	[ $var -eq 0 ]
do
	echo Inside the loop: $var
	var=$[ $var - 25 ]
done
