#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2021/12/31
#=======================

# breaking out of a outer loop

for ((a = 1; a < 4; a++))
do
	echo "Outer loop: $a"
	for ((b = 1; b < 100; b++))
	do
		if [ $b -gt 4 ]
		then
			break 2
		fi
		echo "   Inner loop: $b"
	done
done
