#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2021/12/31
#=======================

# testing $* and $@
echo
echo "Using the \$* method: $*"
echo 
echo "Using the \$@ method: $@"
