#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2022/01/01
#=======================

# demonstrating a multi-position shift

echo "The original parameters: $*"
shift 2
echo "Here's the new first parameter: $1"
