#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2021/12/31
#=======================

# using one command line parameter

factorial=1
for ((number = 1; number <= $1; number++))
do
	factorial=$[ $factorial * $number ]
done
echo The factorial of $1 is $factorial
