#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2022/01/01
#=======================

# demonstrating shift command
count=1
while [ -n "$1" ]
do
	echo "Parameter #$count = $1"
	count=$[ $count + 1 ]
	shift
done
